language: python
python:
  - '3.6'
cache:
  pip: true
dist: trusty
addons:
  postgresql: '9.6'
env: DATABASE_URL=postgres://adpqun:adpqpw@localhost/adpqdb TWILIO_ACCOUNT=Nothing
install:
  - psql -h localhost -c "CREATE USER adpqun WITH SUPERUSER PASSWORD 'adpqpw'";
  - psql -h localhost -c "CREATE DATABASE adpqdb WITH OWNER adpqun";
  - pip install -r requirements.txt
script:
  - ./test.py
